### ISSUE TITLE
🚀 [ Distract Me ] [ Home ]: As a user I want to see all the different distraction options.

### ISSUE THREAD

**Issue by sebastianricaldoni** [CS342/2023-Balance#42]
### Use Case

Once the user is logged in we will display the Home Screen. In this home screen we will render, as the first option, a button to navigate to the Distract Me section.
This task is about rendering such screen with the sections listed below and also offering navigation to the previous screen.

#### Look at Pictures
<img width="320" alt="image" src="https://user-images.githubusercontent.com/397567/228231000-1208421c-6c79-4294-a8c4-e70520174f53.png">

#### Listen to Music
<img width="322" alt="image" src="https://user-images.githubusercontent.com/397567/228231090-b5ee830c-c9d4-45e9-aae4-ae6abc7a2256.png">
 
#### Look Videos
<img width="324" alt="image" src="https://user-images.githubusercontent.com/397567/228231139-ac3550c3-ab36-41ce-a572-9058559db738.png">

#### Games
<img width="332" alt="image" src="https://user-images.githubusercontent.com/397567/228231196-90d18641-4640-4777-9964-681e7c685888.png">

#### Write Something
<img width="337" alt="image" src="https://user-images.githubusercontent.com/397567/228231258-c42915f4-e402-43f3-98c3-74fa48ee0d40.png">

#### Drawing Something
<img width="326" alt="image" src="https://user-images.githubusercontent.com/397567/228231335-f700a34f-9a96-4250-ace0-71e2a84f09c6.png">

## Tech Spec
The images displayed above can get obtained from [this Figma](https://www.figma.com/file/3gqTcN9RctBW2RQIwetey3/Balance?node-id=349-39881&t=A6bBkiEuuTywJQI7-0)

### Problem

N/A

### Solution

N/A

### Alternatives considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by gperissetcelteeka** [comment]
Done
