### ISSUE TITLE
🚀 [Misc] - Project setup

### ISSUE THREAD

**Issue by sebastianricaldoni** [CS342/2023-Balance#47]
### Use Case

This issue is to add some structure and order to the project as well as some POCs.

### Problem

N/A

### Solution

N/A

### Alternatives considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by gperissetcelteeka** [comment]
Re open to fix swiftlint errors
