### ISSUE TITLE
🚀 [ Distract Me ] - [ Play a Game ] : Home screen for listing available online games such as Sudoku

### ISSUE THREAD

**Issue by sebastianricaldoni** [CS342/2023-Balance#52]
### Use Case

As a user I want to be able to distract by playing some online games such as Sudoku, puzzles and crosswords
<img width="268" alt="image" src="https://user-images.githubusercontent.com/397567/230723135-ae5d0dbf-3168-479c-95b0-b37abf897ee4.png">

### Technical Specification
The list of available categories should be configurable, in other words, this list should be dynamic and not static / hardcode.

### Problem

N/A

### Solution

N/A

### Alternatives considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by gperissetcelteeka** [comment]
The integration with the service is still missing
